name: labelsafe_ai
description: "LabelSafe AI - Global product safety transparency app."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lucide_icons: ^0.257.0
  lottie: ^2.7.0
  camera: ^0.10.5+8
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.8.3
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  google_generative_ai: ^0.4.5
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  fl_chart: ^1.1.1
  upgrader: ^12.3.0
  supabase_flutter: ^2.12.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/vectors/
    - .env

